import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'
import Image from 'next/image'
import BImage from '../components/Image/image'
import Header from '../components/Header/header'
import Footer from '../components/Footer/footer'
import Footer2 from '../components/Footer/foot2'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Map/>
        <BImage/>
        <Header/>
        <Footer/>
        <Footer2/>
      </main>
    </>
  )
}
